apiVersion: skaffold/v2beta25
kind: Config
deploy:
  kustomize:
    paths:
      - kustomize/base

profiles:
  - name: build-and-deploy
    activation:
      - command: dev
      - command: debug
    build:
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      local:
        push: false
      artifacts:
        - image: corda-os-docker-dev.software.r3.com/corda-os-p2p-gateway
          context: ../..
          custom:
            buildCommand: gradlew :applications:p2p-gateway:clean -q && gradlew :applications:p2p-gateway:publishOSGiImage -q
            dependencies:
              paths:
                - ./**/*.kt
                - ./**/*.java

  - name: enable-ingress
    deploy:
      kustomize:
        paths:
          - kustomize/overlays/ingress
