apiVersion: v1
kind: ConfigMap
metadata:
  name: p2p-gateway
data:
  KAFKA_SERVERS: kafka-kafka-bootstrap.default.svc.cluster.local:9092
  CONFIG_TOPIC: config-topic
  TOPIC_PREFIX: p2p-gateway
