---
apiVersion: skaffold/v2beta25
kind: Config
profiles:
  - name: deploy
    activation:
      - command: run
    deploy:
      kustomize:
        paths:
          - kustomize/base

  - name: build and deploy
    activation:
      - command: dev
      - command: debug
      - kubeContext: minikube
    build:
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      local:
        push: false
      artifacts:
        - image: corda-os-docker-dev.software.r3.com/corda-os-http-rpc-gateway
          context: ../..
          custom:
            buildCommand: gradlew :applications:http-rpc-gateway:clean -q && gradlew :applications:http-rpc-gateway:publishOSGiImage -q
            dependencies:
              paths:
                - ./**/*.kt
                - ./**/*.java
    deploy:
      kustomize:
        paths:
          - kustomize/base

  - name: overlay-ingress
    deploy:
      kustomize:
        paths:
          - kustomize/base
          - kustomize/overlays/ingress
