---
apiVersion: skaffold/v2beta25
kind: Config
deploy:
  helm:
    releases:
      - repo: https://strimzi.io/charts/
        remoteChart: strimzi-kafka-operator
        name: kafka-operator
  kubectl:
    manifests:
      - manifest/*
    hooks:
      after:
        - host:
            # Stand-in for readiness check of operator managed resource. TODO: Add linux/darwin
            command: [ "cmd.exe", "/C", "kubectl wait --for=condition=Ready=True kafka/kafka"]
            os: [windows]
