apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "corda.fullname" . }}-create-topics
  labels: &id012
    app: create-topics
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels: *id012
    spec:
      containers:
        - name: create-topics
          image: bitnami/kafka:3.1.0-debian-10-r89
#          imagePullPolicy: Always
          command:
            - /bin/sh
            - -e
            - -c
          args: ["echo", "'Topic creation finished'"]
      initContainers:
        - name: create-topic-script
          image: {{ include "corda.bootstrapImage" . }}
          args: [ 'topic', 'create', '-a', '{{ include "corda.kafkaBootstrapServers" . }}', '-l', '/tmp/working_dir/create-topics.sh' ]
          volumeMounts:
            - mountPath: /tmp/working_dir
              name: working-volume
        - name: run-topic-script
          image: bitnami/kafka:latest
#          imagePullPolicy: Always
          command: [ "/bin/sh", "/tmp/working_dir/create-topics.sh" ]
          volumeMounts:
            - mountPath: /tmp/working_dir
              name: working-volume
      volumes:
        - name: working-volume
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 0

