---
apiVersion: skaffold/v2beta25
kind: Config
deploy:
  helm:
    releases:
      - repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
        remoteChart: postgres-operator
        name: postgres-operator
  kubectl:
    manifests:
      - manifest/*
#    TODO: This needs a little work...
#    hooks:
#      after:
#        - host:
#            # Stand-in for readiness check of operator managed resource. TODO: Add linux/darwin
#            command: [ "cmd.exe", "/C", "kubectl wait --for=condition=Ready pods -l cluster-name=corda-postgres" ]
#            os: [windows]
